url: http://mission.tcbc2001.com
baseurl: 
google_analytics_key:

collections:
  staff_members:
    _hide_content: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script id="ch_cdn_embed" type="text/javascript" data-page-id="35706" data-cfasync="false" data-formtype="0" src="https://www.canadahelps.org/services/wa/js/apps/donatenow/embed.min.js"></script>'
newsletter_action: "//samaritanspurse.us8.list-manage.com/subscribe/post?u=690a2902e67269d60406e6b56&amp;id=f507ab4234"
