url: http://mission.tcbc2001.com
baseurl: 
google_analytics_key:

collections:
  staff_members:
    _hide_content: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_one_dollar_a_day: '<A HREF="https://www.canadahelps.org/en/pages/page/new/?charity=109462&fund=222531"><IMG SRC="https://www.canadahelps.org/image/FundRaiseNow/en/FundRaiseNow3.png" BORDER="0" ALT="Fundraise Now Through CanadaHelps.org!"/></A>'
donation_mission_donation: '<A HREF="https://www.canadahelps.org/en/pages/page/new/?charity=109462&fund=225313"><IMG SRC="https://www.canadahelps.org/image/FundRaiseNow/en/FundRaiseNow1.png" BORDER="0" ALT="Fundraise Now Through CanadaHelps.org!"/></A>'
newsletter_action: "//samaritanspurse.us8.list-manage.com/subscribe/post?u=690a2902e67269d60406e6b56&amp;id=f507ab4234"
